### ISSUE TITLE
"Gourmet does not have a plugin capable of importing URL"

### ISSUE THREAD

**Issue by Lamecarlate** [thinkle/gourmet#865]
Hi! 

I can't import recipes from websites anymore.

Tested, for example, on this page: http://minimalistbaker.com/coconut-curried-greens-30-minutes/ . I know it used to work on this site, because the very first recipe I imported in Gourmet is this one: http://minimalistbaker.com/best-ever-5-minute-microwave-hummus/. I used to be able to import from various cooking blogs & sites, not just Epicurious or that sort of big sites.

The error I have is this one: "Gourmet does not have a plugin capable of importing URL".

Gourmet version 0.17.4
OS Ubuntu GNU/Linux 17.04
Plugin "Webpage import" activated

Is there anybody with the same issue?

**Comment by oktexan** [comment]
I had the same issue in gentoo.  I neglected to have the correct USE flags set to enable web imports.  Once I corrected that issue, it started working.  I noticed that when I rebuilt the gourmet package, it pulled in BeautifulSoup 3.2.1-r1.  Have you confirmed you have that installed?  I believe it would be called python-beautifulsoup on Ubuntu.  It's listed as a recommended package but I don't think apt-get automatically installs it on Ubuntu...sorry but it's been a while since I've used a debian based distro.

**Comment by utricularia** [comment]
@oktexan How do you set those USE flags? I am trying to get this feature working so I can contribute some enhancements.

**Comment by oktexan** [comment]
web is the USE flag you need to get it working...here is a paste of the use flags I'm currently using for gourmet if that helps:

# required by dev-python/sqlalchemy-1.0.17::gentoo[python_targets_python3_4]
# required by app-misc/gourmet-0.17.4-r1::gentoo
# required by app-misc/gourmet (argument)
>=dev-lang/python-3.4.5 sqlite

>=app-misc/gourmet-0.17.4-r1 pdf print spell sound web

**Comment by Lamecarlate** [comment]
I'm sorry I didn't answer sooner… In fact, on day, it worked without I did anything, so I forgot about here. 

But a few weeks ago I upgraded from Ubuntu 17.10 to 18.04 (it was about time), and Gourmet couldn't import anymore. So I typed

`sudo apt install python-beautifulsoup`

And then Gourmet imported again. So, this package is really the solution (for users with `apt`).

(and I can finally close this issue, thanks very much to all participants)
