### ISSUE TITLE
.grmt won't import?

### ISSUE THREAD

**Issue by MarkP2015** [thinkle/gourmet#941]
For a period of a year, I couldn't get GRM to import/export (doh! my bad!). So each recipe was exported individually, one by one. Now I've refurbished GRM and am trying to import those files saved or exported as .grmt and I cannot import that.

Do I need to convert .grmt into another format? I tried renaming to .xml but GRM won't see that under Import, either.

**Comment by saxon-s** [comment]
In order to reproduce the problem, please clarify the following ... 

1. What is the Gourmet version number?
2. What is the host OS and version? 
3. What do you mean by "refurbished GRM"? 
4. What are the steps you performed to export the .grm files?
5. What are the steps you performed to import the .grm files?
